### PR TITLE
FIX: do not skip isolated points in vector outputs

### LINKED ISSUE #7293: Isolated points missing in pdf
Dear developers,
when plotting single points surrounded by np.nan values, points are shown in a regular plot, but are omitted when saved via pdf backend. Minimal example:

```
import numpy as np
import matplotlib.pyplot as plt

a = np.array([1,np.nan,2,np.nan,3,3.5,4])

plt.plot(a, marker='o')
plt.show()
```

generates a perfect plot with the 5 points shown:

foo1

but directly saving it via pdf backend omitts the values isolated by np.nans:

```
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.backends.backend_pdf as pdf

a = np.array([1,np.nan,2,np.nan,3,3.5,4])

fig1 = plt.figure()
sub  = fig1.add_subplot(1,1,1)
sub.plot(a,marker='o')
pp1  = pdf.PdfPages('foo.pdf')
fig1.savefig(pp1, format='pdf')
pp1.close()
```

like so:

foo2

I would be glad for any help.

System:
Ubuntu 14.02
Python 2.7.6
Numpy 1.11.2
Matplotlib 1.5.3

### PR DESCRIPTION
**Pull request by tacaswell**
Fixed bug in path interaction code where multiple moves in a
row (which correspond to isolated points surrounded by nans after they
have been filtered from the path) would be discarded which resulted in
points not being plotted.

closes #7293

### CODE REVIEW

File: src/path_converters.h [hunk 1]
```diff
@@ -363,10 +366,30 @@ class PathClipper : public EmbeddedQueue<3>
                     goto exit_loop;
 
                 case agg::path_cmd_move_to:
+
+		    // was the last command a move to (and we have
+		    // seen at least one command ?
+		    // if so, shove it in the queue if in clip box
+		    if (m_moveto && m_has_init &&
+			m_lastX >= m_cliprect.x1 &&
```
Comment (QuLogic) [inline src/path_converters.h]: I prefer reversing the arguments here so that it looks similar to Python's chained form.

File: src/path_converters.h [hunk 2]
```diff
@@ -363,10 +366,30 @@ class PathClipper : public EmbeddedQueue<3>
...
+			m_lastX <= m_cliprect.x2 &&
+			m_lastY >= m_cliprect.y1 &&
+			m_lastY <= m_cliprect.y2) {
+			// push the last moveto onto the queue
```
Comment (QuLogic) [inline src/path_converters.h]: moveto -> move to (or maybe the reverse for the other places would be clearer.)

Comment (QuLogic) [inline src/path_converters.h]: Actually, this comment is kind of redundant with the one above the `if`.

File: src/path_converters.h [hunk 3]
```diff
@@ -363,10 +366,30 @@ class PathClipper : public EmbeddedQueue<3>
...
+                        queue_push(agg::path_cmd_move_to, m_lastX, m_lastY);
+			// flag that we need to emit it
+			emit_moveto = true;
+                    }
+		    // update the internal state for this move to
                     m_initX = m_lastX = *x;
                     m_initY = m_lastY = *y;
                     m_has_init = true;
                     m_moveto = true;
+		    // if the last command was move to exit the loop to emit the code
```
Comment (QuLogic) [inline src/path_converters.h]: I mean, this is pretty clearly what it does already, so it's kind of a redundant comment. Would be better as a why instead of a what.

**Comment by tacaswell** [comment]
Have not bisected, but looking at the blame I suspect this was broken by #5911 so broken from 1.5.2 on.

File: src/path_converters.h [hunk 4]
```diff
@@ -343,6 +343,7 @@ class PathClipper : public EmbeddedQueue<3>
     unsigned vertex(double *x, double *y)
     {
         unsigned code;
+	bool emit_moveto = false;
```
Comment (tacaswell) [inline src/path_converters.h]: gah! emacs has betrayed me!

File: src/path_converters.h (hunk 1 above)
Comment (tacaswell) [inline src/path_converters.h]: This matches the block further down, would rather stay consistent with that.

File: src/path_converters.h [hunk 5]
```diff
@@ -363,10 +366,30 @@ class PathClipper : public EmbeddedQueue<3>
...
+
+                    // was the last command a moveto (and we have
+                    // seen at least one command ?
+                    // if so, shove it in the queue if in clip box
+                    if (m_moveto && m_has_init &&
+                        m_lastX >= m_cliprect.x1 &&
+                        m_lastX <= m_cliprect.x2 &&
+                        m_lastY >= m_cliprect.y1 &&
+                        m_lastY <= m_cliprect.y2) {
+                        // push the last moveto onto the queue
```
Comment (QuLogic) [inline src/path_converters.h]: I think this comment is still redundant.

Comment (tacaswell) [inline src/path_converters.h]: I wrote this as comments to my self while understanding this.  I do not see a problem with leaving them.

**Comment by NelleV** [comment]
Thanks @tacaswell !

**Comment by tacaswell** [comment]
This PR was about 2 LoC / hr :laughing:
