### PR TITLE
Fix leak if affine_transform is passed invalid vertices.

### LINKED ISSUE #20641: Memory leak in function matplotlib._path.affine_transform
### Bug report
When I input an illegal value into the function matplotlib._path.affine_transform, the memory use is increasing as the number of calls.

**Code for reproduction**
```
import sys
import tracemalloc
import numpy
import matplotlib._path

arg_list = []
arg_list.append(True)
arg_list.append(True)
arg_list.append(False)
arg_list.append(False)
arg_list.append(False)
arg_list.append(False)
arg_list.append(False)
arg_list.append(False)
arg_list.append(False)

memory_recorder = []
tracemalloc.start()
start_snapshot = tracemalloc.take_snapshot()
for i in range(0, 100):
  try:
    matplotlib._path.affine_transform([], numpy.array(
      [[arg_list[0], arg_list[1], arg_list[2]], [arg_list[3], arg_list[4], arg_list[5]],
       [arg_list[6], arg_list[7], arg_list[8]]]))
  except:
    pass
  if i % 10 == 0:
    one_snapshot = tracemalloc.take_snapshot()
    memory_recorder.append(one_snapshot.compare_to(start_snapshot, 'lineno')[0])

for i in range(2, len(memory_recorder)):
  print(memory_recorder[i].traceback)
  print(memory_recorder[i].size)

tracemalloc.stop()
```

**Actual outcome**
```
test.py:22
2497
test.py:22
3617
test.py:22
4737
test.py:22
5809
test.py:22
6977
test.py:22
8049
test.py:22
9217
test.py:22
10337
```
As the output shows, the memory use of line 22 is increasing as the number of calls increases.

I install matplotlib from source code via command pip3 install -e .
and the version is commit 9e0bb9c72121a7c3ba85c55368ae402bbfdd7782

### PR DESCRIPTION
**Pull request by QuLogic**
## PR Summary

`CALL_CPP` may raise an exception, so we should drop the `vertices` ref before calling it. We've already added an automatically-dropping ref with the `array_view`, so we don't need this one.

Fixes #20641.

## PR Checklist

- [x] Has pytest style unit tests (and `pytest` passes).
- [x] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [n/a] New features are documented, with examples if plot related.
- [n/a] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [x] Conforms to Matplotlib style conventions (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).
- [n/a] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [n/a] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

### CODE REVIEW

File: src/_path_wrapper.cpp [hunk 1]
```diff
@@ -454,16 +454,18 @@ static PyObject *Py_affine_transform(PyObject *self, PyObject *args, PyObject *k
     if (PyArray_NDIM(vertices_arr) == 2) {
         numpy::array_view<double, 2> vertices(vertices_arr);
         npy_intp dims[] = { (npy_intp)vertices.size(), 2 };
+        Py_DECREF(vertices_arr);
```
Comment (anntzer) [inline src/_path_wrapper.cpp:457]: perhaps move it even before declaring/initing `dims[]`?  interleaving it in the middle of creating `results` is a bit weird...
(ditto below)

**Review by anntzer — APPROVED** [review]
modulo the minor point above being addressed (or explicitly rejected)

**Review by timhoffm — APPROVED** [review]

File: src/_path_wrapper.cpp (hunk 1 above)
Comment (QuLogic) [reply src/_path_wrapper.cpp:457]: I just misread `vertices` as the thing we were using originally.

**Comment by jklymak** [comment]
Feel free to self-merge when CI is done!
