### PR TITLE
FIX: macos: Use standard NSApp run loop in our input hook

### LINKED ISSUE #28960: [Bug]: High CPU utilization of the macosx backend
### Bug summary

After showing interactive figure, the CPU utilization of python process went to 100%.

### Code for reproduction

```Python
#######################################################
# Case 1: 100% cpu
import matplotlib.pyplot as plt
fig = plt.figure()
plt.plot(range(5))
plt.show()
# after closing the window
import pandas              # starting 100% CPU utilization

#######################################################
# Case 2: 100% cpu
import matplotlib.pyplot as plt
import pandas as pd

# No CPU utilization at the moment

fig = plt.figure()
df = pd.DataFrame(range(5))

plt.plot(df[0])           # with this, CPU utilization is 100%.
plt.show()                 # the same

# after closing the window, still 100%

#######################################################
# Case 3: no issue.
import matplotlib.pyplot as plt
fig = plt.figure()
plt.plot(range(5))
plt.show()              # strangely, this has no problem.
```

### Actual outcome

no problem except it consumes 100% cpu.   The figure is still responsive.

### Expected outcome

matplotlib backend should not consume 100% cpu.

### Additional information

- pandas version 2.2.3 (pip)

- Certain operation (closing interactive figures) causes 100% cpu with 'macosx' backend.  
- Closing the figure, or calling `plt.close()` does not help.  (backend: macosx)
- No problem with `qt5agg` backend.

### Operating system

Mac (Intel) Ventura 13.6.6

### Matplotlib Version

3.9.2

### Matplotlib Backend

macosx

### Python version

Python 3.12.3

### Jupyter version

_No response_

### Installation

pip

### PR DESCRIPTION
**Pull request by greglucas**
## PR summary

We want to defer back to Python's native input hook handling when we don't have any figures to interact with, otherwise our runloop will continue running unecessarily.

Additionally, we need to add a short runloop burst in our hotloop to avoid saturating the CPU while waiting for input. (i.e. sitting on an idle figure would keep 100% cpu while waiting for an input() event without this runloop trigger).

closes #28960

## PR checklist

- [x] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [n/a] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [n/a] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/document.html#write-examples-and-tutorials)
- [n/a] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/api_changes.html#announce-changes-deprecations-and-new-features)
- [n/a] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/document.html#write-docstrings) guidelines

### CODE REVIEW

**Comment by greglucas** [comment]
Running the example from https://github.com/matplotlib/matplotlib/issues/26869 on current main and waiting for `input()` would produce 100% cpu too. So the fix in https://github.com/matplotlib/matplotlib/pull/27528 to remove the runloop call actually caused that 100% cpu usage because the while(True) is running too frequently and saturating the CPU.

The removal of the runloop timer was to fix this issue: https://github.com/matplotlib/matplotlib/issues/27515 I think that was the wrong "fix" of the issue, and the real way to fix that issue is to remove our own input hook and yield back to Python's terminal handling.

In all of these examples, we should be at minimal CPU usage when sitting still. I'm still not sure how we could test/verify this? But it would be nice to add something to make sure we don't regress on this in the future.

File: src/_macosx.m [hunk 1]
```diff
@@ -1122,7 +1128,7 @@ - (void)close
 {
     [super close];
     --FigureWindowCount;
-    if (!FigureWindowCount) [NSApp stop: self];
+    if (!FigureWindowCount) stop(NULL);
```
Comment (QuLogic) [inline src/_macosx.m:1131]: This leaks the `None` reference returned from `stop` (at least on versions before it became immortal).

Comment (greglucas) [reply src/_macosx.m]: 👍 Added a decref to the return object now. I could change this back to the original `[NSApp stop: self]` and add the `PyOS_InputHook = NULL` call here too instead if that is better? I just figured it might be nice to try and go through one stop function everywhere we need it, although it is only in two places currently.

**Comment by tacaswell** [comment]
@ksunden and I spent a while looking at this on Friday, but not sure where that landed / if he pushed anything.

**Comment by greglucas** [comment]
Feel free to push directly here or open a separate PR and I'm happy to review it too.

**Comment by ksunden** [comment]
You can see what I have been trying in https://github.com/ksunden/matplotlib/tree/macos-pyos-input-hook

Essentially:

- removing the hook actually causes some problems (most notably `plt.close("all")` did not actually close windows until the event loop was started again)
- If we don't remove the hook, I don't _think_ there is much reason to change around the other stopping logic here.
- I think this PR only solves the CPU usage by virtue of inserting what effectively amounts to a sleep
  - In changing things, I went to just run the loop and adjust how we break from the loop, I discovered that it appears that the loop referenced here is not actually the main app runloop, so effectively the new line is just a sleep.
  - I can get mostly working replacing our entire double while loop setup with `[NSApp run];`, but run into problems after closing plots (specifically via the window's X button) wherein a single character is processed by the repl, but then it hangs with 160% CPU usage and I'm not sure where/why.

**Comment by greglucas** [comment]
FYI, I think v3.6.3 is where some of this logic was referenced from with the double loop and breaking out of it: https://github.com/matplotlib/matplotlib/blob/abcbf3d11524fa53b08243bc0aa85dd942439454/src/_macosx.m#L149-L169
specifically, there was the call to the cfrunloop: https://github.com/matplotlib/matplotlib/blob/abcbf3d11524fa53b08243bc0aa85dd942439454/src/_macosx.m#L158
which is what the "sleep" you mention is from.

File: src/_macosx.m [hunk 2]
```diff
@@ -40,60 +40,84 @@
...
 }
 
 static int wait_for_stdin() {
-    @autoreleasepool {
-        stdin_received = false;
-        stdin_sigint = false;
+    // Short circuit if no windows are active
+    // Rely on Python's input handling to manage CPU usage
+    // This queries the NSApp, rather than using our FigureWindowCount because that is decremented when events still
+    // need to be processed to properly close the windows.
```
Comment (tacaswell) [inline src/_macosx.m:87]: This will also make us play nicer with any other OSX apps you launch from Python (which I am not aware of any others....)

File: src/_macosx.m [hunk 3]
```diff
@@ -192,16 +216,16 @@ void process_event(char const* cls_name, char const* fmt, ...)
 static bool backend_inited = false;
 
 static void lazy_init(void) {
+    // Run our own event loop while waiting for stdin on the Python side
+    // this is needed to keep the application responsive while waiting for input
+    PyOS_InputHook = wait_for_stdin;
```
Comment (tacaswell) [inline src/_macosx.m:221]: can probably move this back down so we are not re-setting it all the time?

File: src/_macosx.m [hunk 4]
```diff
@@ -40,60 +40,84 @@
...
+
+// Helper function to flush all events.
+// This is needed in some instances to ensure e.g. that windows are properly closed.
+// It is used in the input hook as well as wrapped in a version callable from Python.
+static void flushEvents() {
+    while (true) {
+        NSEvent* event = [NSApp nextEventMatchingMask: NSEventMaskAny
+                                   untilDate: [NSDate distantPast]
+                                      inMode: NSDefaultRunLoopMode
+                                     dequeue: YES];
```
Comment (greglucas) [inline src/_macosx.m:75]: We've been aligning on `:` it seems like, so suggest doing the same here and below after the `notificationID` indent now.

The name of this function is `flushEvents()` but above you added `stop_with_event()` is there a common form we want to use between them?

```suggestion
        NSEvent* event = [NSApp nextEventMatchingMask: NSEventMaskAny
                                            untilDate: [NSDate distantPast]
                                               inMode: NSDefaultRunLoopMode
                                              dequeue: YES];
```

File: src/_macosx.m (hunk 2 above)
Comment (greglucas) [reply src/_macosx.m:87]: Should we use this method in the `close()` method too instead of keeping track of it ourselves?

**Review by greglucas — COMMENTED** [review]
Nice updates @ksunden, thanks for pushing those!

I verified that this new change fixes the slow input typing lag regression I saw before as well.

File: src/_macosx.m (hunk 2 above)
Comment (greglucas) [reply src/_macosx.m:87]: There are some folks embedding this in C++/objc it would appear: https://github.com/matplotlib/matplotlib/issues/27147

Comment (tacaswell) [reply src/_macosx.m:87]: That is its own bit of fun, but I think this will not intersect with that issue because the only place the `PyOS_InputHook` is run is from the Python repl (either readline or the new one) so if they are embedding Python in another application (which means they make an interpreter object and then stuff strings into it to run Python code) so I expect the repl will never run.

**Review by tacaswell — APPROVED** [review]
But I was on a call with Kyle as we worked through this so this should probably count as less than 1 full review.

**Comment by greglucas** [comment]
I have run through this with a few different test cases as well and it looks good to me and is a nice simplification. It has been significantly changed by @ksunden, so I would consider it his PR now :) I "approve", although I can not technically click the button on my own PR.

**Comment by tacaswell** [comment]
I'm going to go ahead and merge this.
