### PR TITLE
Fix up some OSX backend issues

### LINKED ISSUE #10948: OSX backend raises deprecation warning for enter_notify_event
**Bug summary**

Opening a figure using the MacOSX backend raises a deprecation warning (see below).

**Code for reproduction**

```python
import matplotlib
matplotlib.use('macosx')
import matplotlib.pyplot as plt
plt.plot([1, 2], [1, 2])
plt.show()
```

**Actual outcome**

```bash
/Users/dstansby/github/matplotlib/lib/matplotlib/backend_bases.py:1993: MatplotlibDeprecationWarning: enter_notify_event expects a location but your backend did not pass one.
  cbook.warn_deprecated('3.0', 'enter_notify_event expects a '
```

**Expected outcome**

**Matplotlib version**

  * Matplotlib version: master branch
  * Matplotlib backend (`print(matplotlib.get_backend())`): MacOSX
  * Python version: 3.6.4

### LINKED ISSUE #11985: Single shot timer not working correctly with MacOSX backend
### Bug report

**Bug summary**

A timer created when using the MacOSX backend and in 'single-shot' mode causes the callback to be called straight away instead of after the specified interval.

**Code for reproduction**

```python
from matplotlib import pyplot as plt

def timercb(e):
    print("timer")

fig, ax = plt.subplots()
timer = fig.canvas.new_timer(interval=5000)
timer.single_shot = True
timer.add_callback(timercb, ax)
timer.start()
plt.show()
```

**Actual outcome**

The script prints out ``timer`` straight away

**Expected outcome**

The script would print out ``timer`` after 5 seconds

**Matplotlib version**

  * Operating system: MacOS X 10.13.6
  * Matplotlib version: 2.2.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): MacOSX
  * Python version: 3.6.4

I am using conda to manage my Python ecosystem

### PR DESCRIPTION
**Pull request by dopplershift**
This fixes up a few issues in the OSX backend:
- Deprecation warning due to lack of position information in `enter_notify_event`. Added position information (this would have been much easier if this event wasn't the **only** one that takes position as a tuple). Liberally borrowed code used in other event handlers in OSX backend. Fixes #10948.
- Incorrect behavior of OSX timer. It turns out by passing a 0 for an API call, we were essentially telling OSX to fire the timer as soon as possible. Fixed to pass proper time for initial firing of timer. Fixes #11985.

### CODE REVIEW

**Comment by dopplershift** [comment]
attn: @astrofrog

**Comment by dopplershift** [comment]
Anyone wanting to check me on the API calls can check out the docs [here](https://developer.apple.com/documentation/corefoundation/1543570-cfrunlooptimercreate?language=objc).

File: src/_macosx.m [hunk 1]
```diff
@@ -1804,8 +1804,20 @@ - (void)mouseEntered:(NSEvent *)event
...
+    int x, y;
+    NSPoint location = [event locationInWindow];
+    location = [self convertPoint: location fromView: nil];
+    x = location.x * device_scale;
+    y = location.y * device_scale;
+
     gstate = PyGILState_Ensure();
-    result = PyObject_CallMethod(canvas, "enter_notify_event", "");
+    PyObject* loc = Py_BuildValue("ii", x, y);
+    Py_INCREF(Py_None);
```
Comment (anntzer) [inline src/_macosx.m]: you can just borrow the ref to None (i.e. don't bother with Py_INCREF/Py_DECREF)

Comment (dopplershift) [reply src/_macosx.m]: Is that because we're staying inside our function? I know we have to inc ref when returning (or use `Py_RETURN_NONE`).

File: src/_macosx.m [hunk 2]
```diff
@@ -1804,8 +1804,20 @@ - (void)mouseEntered:(NSEvent *)event
...
+    result = PyObject_CallMethod(canvas, "enter_notify_event", "OO",
+            Py_None, loc);
```
[the remark this answers is not in the document]
Comment (dopplershift) [reply src/_macosx.m]: Ah, that's a new one.

**Comment by dopplershift** [comment]
Well that simplifies the one commit significantly.

File: src/_macosx.m (hunk 1 above)
Comment (anntzer) [reply src/_macosx.m]: yup

**Comment by astrofrog** [comment]
@dopplershift - thanks for the timer fix!

**Comment by jklymak** [comment]
Thanks @dopplershift!
