### PR TITLE
Fix mathtext image bounding box

### LINKED ISSUE #4147: Problems with text that is just a LaTeX minus sign
I just discovered that a legend with label `'$-$'`, i.e., a single math-mode minus sign, has a number of problems in png output (which also is problematic for ipython notebook inline plots, but the error is independent of that). The exact problem depends on the dpi that the figure is saved with. Here's a minimal example to reproduce it:
```python
import matplotlib.pyplot as plt
plt.plot([0,1],[1,0])
plt.legend(['$-$'])
plt.savefig('test.png',dpi=120)
```

For some settings of dpi, I get an error message with a traceback ending in 
```python
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 187, in draw_text
    return self.draw_mathtext(gc, x, y, s, prop, angle)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 178, in draw_mathtext
    self._renderer.draw_text_image(font_image, x, y + 1, angle, gc)
ValueError: First argument to draw_text_image must be a FT2Font.Image object or a Nx2 uint8 numpy array.
```
while for other settings of dpi, the PNG is generated but the minus sign does not show up (i.e., the legend is empty). Both only happens if the minus sign is the only character in the legend - although it also happens with two minus signs `$--$`, and even a dash and a minus sign `-$-$`, but not with only a dash `-`, or if I add any other character (as far as I have tested).
The exact settings of dpi where I get the error and where the minus sign disappears from the output are apparently system-dependent, but it always disappears for high enough dpi (>93 on one system), and the errors typically show up in the range 120<dpi<140 - for higher dpi, there is again no error, but the symbol is not shown either.

I have tested this on two different systems (OS X with matplotlib 1.4.2 from MacPorts and Red Hat with matplotlib 1.4.3 from anaconda), and with both python 2.7 and python 3.4 on the OS X system, and it shows up on all of them.

### PR DESCRIPTION
**Pull request by mdboom**
This fixes #4147, so that characters with a negative depth (such as the minus sign) are not arbitrarily clipped.

Going down that rabbit hole, discovered two other bugs related to text buffers, including a buffer overrun.

Fix #4147.

### CODE REVIEW

**Comment by mdboom** [comment]
I seem to be getting the same test failures on master as this (but Travis hasn't tested master in 5 days).  Not sure what's up there...

**Comment by tacaswell** [comment]
Some how travis got turned off

**Comment by mdboom** [comment]
No worries -- in any event, it seems to be back on and master is passing.  I'll restart this PR's build on Travis and see how it works now.

**Comment by mdboom** [comment]
Ok -- I think we're back in business.  This is ready for a final review.

File: src/ft2font.cpp [hunk 1]
```diff
@@ -146,11 +146,11 @@ FT2Image::draw_rect_filled(unsigned long x0, unsigned long y0, unsigned long x1,
...
     x0 = std::min(x0, m_width);
     y0 = std::min(y0, m_height);
-    x1 = std::min(x1, m_width);
-    y1 = std::min(y1, m_height);
+    x1 = std::min(x1 + 1, m_width);
+    y1 = std::min(y1 + 1, m_height);
 
-    for (size_t j = y0; j < y1 + 1; j++) {
-        for (size_t i = x0; i < x1 + 1; i++) {
+    for (size_t j = y0; j < y1; j++) {
```
Comment (tacaswell) [inline src/ft2font.cpp]: This changes the limits in the case where `m_width` is the minimum, is that intentional?

Comment (mdboom) [inline src/ft2font.cpp]: Yes.  x0 and x1 represent an inclusive range here, i.e. to fill, say, a one pixel line at pixel 5, x0 == 5, and x1 == 5.  (One could argue that's not the best interface, but it's what we have).  The problem is that occasionally, the line requested goes outside of the edge of the image, and we need to protect against that at all costs (because that would be a buffer overflow).  This wasn't an issue in practice until the bounds of the image was corrected to something more accurate in `mathtext.py`.
