### PR TITLE
Fixed inaccurate image placement and even more resampling bugs

### LINKED ISSUE #31009: [Bug]: Large pixels may overlap when using imshow()
### Bug summary

When using `imshow()` with a small array (large pixels), the pixel patches can end up slightly misaligned. This becomes especially obvious when thin grid lines are overlaid on the figure.

### Code for reproduction

```Python
import matplotlib.pyplot as plt
import numpy as np

fig,ax = plt.subplots() 
N = 12 
ax.imshow(np.random.rand(N, N)) 
seps = np.arange(-0.5, N) 
ax.vlines(seps, -0.5, N - 0.5, linewidth=1)
ax.hlines(seps, -0.5, N - 0.5, linewidth=1)
plt.show()
```

### Actual outcome

Image

### Expected outcome

A figure where none of the pixel patches overlap their respective grid lines.

### Additional information

I originally thought this was the same issue as #14143, see [my original comment](https://github.com/matplotlib/matplotlib/issues/14143#issuecomment-584833923). Eventually that bug was fixed but this issue remained. [To quote @ayshih](https://github.com/matplotlib/matplotlib/issues/14143#issuecomment-3781269196):

> Based on my investigation so far, the problem in your example is indeed distinct from the original issue, and it is very important to fix. It's not a bug internal to the image-resampling code, but rather it has to do with how image placement affects what resampling is requested and how the resampled image is drawn.

### Operating system

Debian

### Matplotlib Version

3.11.0.dev1652+gddd4196c7 (but first found around 3.3.0)

### Matplotlib Backend

_No response_

### Python version

_No response_

### Jupyter version

_No response_

### Installation

uv

### PR DESCRIPTION
**Pull request by ayshih**
## PR summary

This PR now fixes a bunch of bugs:
* Misaligned placement of `AxesImage`, `PcolorImage`, and `NonUniformImage`
* Interpolation inaccuracies when affine resampling under nearest-neighbor interpolation
* Edge effects when affine resampling under nearest-neighbor interpolation
* Reflected data beyond the image bounds when nonaffine resampling under nearest-neighbor interpolation
* Alpha/color issues at the edges when affine resampling under non-nearest-neighbor interpolation in RGBA space

---
Original post:

This PR fixes a bug with how images are resampled for drawing when they are positioned at a fractional pixel (which is nearly always the case).  The existing code resamples the image to the (mostly) correct width/height in display pixels, but essentially assumes that the beginning edge of the display array is aligned with the beginning edge of the image array.  This resampled image is then placed at the nearest display pixel, which combined with above, means that the drawn image can be up to a pixel off from the optimal location.

The "mostly" above is because the above bug means that the drawn image can leave a gap to the axes at the end edge of the drawn image, so there's additional, discomforting code to slightly enlarge the resampled image to cover up that gap.  This additional code runs only for affine transformations, so you can see the gap when using a nonaffine transformation.

### Before this PR:
before

This PR fixes the resampling logic so that it anticipates the rounding that will be used in the later drawing and defines the transform appropriately with the rounding baked in.  That way, each display pixel has been resampled exactly correctly to match the eventual drawing.  Furthermore, this means there are should no longer any gaps at the end edge of the drawn image, so there no longer needs to be an enlarging step.

The resampling code for nonaffine transforms has already been scrubbed extensively (#30054 and #30184), so drawing using a nonaffine transform now gives optimal results with this PR.

~Unfortunately, while drawing using an affine transform is also broadly improved, there are still cases where the results are not optimal due to inaccuracies in the image-resampling code for affine transforms.  See https://github.com/matplotlib/matplotlib/pull/30184#issuecomment-3348008749 for some details.  I'm mulling over whether to greatly expand the solution described in https://github.com/matplotlib/matplotlib/pull/30184#issuecomment-3382204882, that is, taking the switching to the nonaffine-transform code path for extreme zooms (>128x) and extending it down to minor zooms (>\~5x).~

Update: I've made changes to how the Agg resampler handles affine transforms when using nearest-neighbor interpolation, and now drawing using an affine transform also gives optimal results.

### After this PR:
after

### Generating script:
```python
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.transforms import Transform

# Create a nonaffine identity to easily convert an affine transform to its nonaffine equivalent
class NonAffineIdentityTransform(Transform):
    input_dims = 2
    output_dims = 2

    def inverted(self):
        return self
nonaffine_identity = NonAffineIdentityTransform()

fig, axs = plt.subplots(2, 3)

N = [3, 7, 11]

for j in range(3):
    data = np.arange(N[j]**2).reshape((N[j], N[j])) % 4
    seps = np.arange(-0.5, N[j])

    for i in range(2):
        if i == 0:
            axs[i, j].imshow(data, cmap='Grays')
            axs[i, j].set_title('affine')
        else:
            axs[i, j].imshow(data, cmap='Grays', transform=nonaffine_identity + axs[i, j].transData)
            axs[i, j].set_title('nonaffine')

        axs[i, j].set_axis_off()
        axs[i, j].vlines(seps, -1, N[j], linewidth=0.5, color='red', linestyle='dashed')
        axs[i, j].hlines(seps, -1, N[j], linewidth=0.5, color='red', linestyle='dashed')

plt.show()
```

Fixes #31009

## PR checklist

- [x] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [x] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [N/A] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/document.html#write-examples-and-tutorials)
- [x] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/api_changes.html#announce-changes-deprecations-and-new-features)
- [N/A] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/document.html#write-docstrings) guidelines

### CODE REVIEW

**Comment by QuLogic** [comment]
Does this replace #30175?

**Comment by ayshih** [comment]
Yes, so I'll close #30175

**Comment by ayshih** [comment]
> I've made changes to how the Agg resampler handles affine transforms when using nearest-neighbor interpolation, and now drawing using an affine transform also gives optimal results.

To elaborate, the issue at hand is that the Agg resampler uses an integer-based interpolator for affine resampling (see some details in https://github.com/matplotlib/matplotlib/pull/30184#issuecomment-3348008749).  The resulting inaccuracies can be obvious when using nearest-neighbor interpolation.  This PR replaces that interpolator with a floating-point-based interpolator, and qualitatively there is no discernable performance hit.

As a nice benefit of this change, the solution described in https://github.com/matplotlib/matplotlib/pull/30184#issuecomment-3382204882 – falling back to nonaffine resampling under extreme zooms – is no longer necessary to preserve the alignment of pixel edges.

To be safe performance-wise, affine resampling under non-nearest-neighbor interpolation continues to use the integer-based interpolator.  Unlike with nearest-neighbor interpolation, it's very difficult to tell if there are slight inaccuracies with the interpolator.  This can be revisited in the future.

**Comment by ayshih** [comment]
Even with the fixing the affine resampling, the resampled image continued to sometimes have a gap at the end.  It turns out that a rendering box was being applied to affine resampling, even under nearest-neighbor interpolation, and that could hinder the rendering of the edges.  Under nearest-neighbor interpolation, the interpolation is now calculated exactly correctly, so there is no longer a need to apply a rendering box, which avoids the occasional appearance of gaps between the image and the axes spines.

The reason for the rendering box was for non-nearest-neighbor interpolation.  To resample up to the edge of the image, the code uses the assumption of reflection wrapping on all edges.  For nearest-neighbor interpolation, this PR now fills to zero beyond the bounds of the source image instead of reflection wrapping, which allows us to avoid a rendering box.

For arbitrary nonaffine resampling, a rendering box cannot be reliably defined, so nonaffine resampling has had the long-standing bug of always showing the reflection wrapping.

### Before this PR
before

The same removal of reflection wrapping done for affine resampling under nearest-neighbor interpolation can be done for nonaffine resampling under nearest-neighbor interpolation, 

### After this PR
after

Fixing the nonaffine resampling under non-nearest-neighbor interpolation is a more challenging problem, and must be deferred to a future effort.

### Generating code
```python
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.patches import Rectangle
from matplotlib.transforms import Affine2D, Transform

# Create a nonaffine identity to easily convert an affine transform to its nonaffine equivalent
class NonAffineIdentityTransform(Transform):
    input_dims = 2
    output_dims = 2

    def inverted(self):
        return self
nonaffine_identity = NonAffineIdentityTransform()

fig, axs = plt.subplots(2, 3)

N = 11

interpolation = ['nearest', 'hanning', 'bilinear']

for j in range(3):
    data = np.arange(N**2).reshape((N, N))
    data = data / N**2 + (data % 4) / 6
    rotation = Affine2D().rotate_around(N/2-0.5, N/2-0.5, 1)

    for i in range(2):
        if i == 0:
            axs[i, j].imshow(data, cmap='Grays', interpolation=interpolation[j],
                             transform=rotation + axs[i, j].transData)
            axs[i, j].set_title(f"{interpolation[j]}\naffine")
        else:
            axs[i, j].imshow(data, cmap='Grays', interpolation=interpolation[j],
                             transform=nonaffine_identity + rotation + axs[i, j].transData)
            axs[i, j].set_title('nonaffine')

        axs[i, j].set_axis_off()
        box = Rectangle((-0.5, -0.5), N, N,
                        edgecolor='red', facecolor='none', lw=0.5, ls='dashed',
                        transform=rotation + axs[i, j].transData)
        axs[i, j].add_artist(box)

plt.show()
```

**Comment by ayshih** [comment]
This PR now also fixes the pixel alignment for `PcolorImage` and `NonUniformImage`.  The coordinates are specified differently (edges versus centers) for these two image types, so the two types are not supposed to agree.  Just look at the pixel alignment to grid lines in the upper right of each panel (away from the yellow/red box).

### Before this PR
before

### After this PR
after

### Generating code
```python
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.image import NonUniformImage
from matplotlib.patches import Rectangle

fig, axs = plt.subplots(2, 3)

N = [4, 9, 11]

for j in range(3):
    data = np.arange(N[j]**2).reshape((N[j], N[j])) % 5
    seps = np.arange(-0.5, N[j] + 1)

    x_edges = np.arange(-0.5, N[j])
    x_edges[2:] += 1
    y_edges = np.arange(-0.5, N[j])
    y_edges[3:] += 1

    x_mids = (x_edges[:-1] + x_edges[1:]) / 2
    y_mids = (y_edges[:-1] + y_edges[1:]) / 2

    for i in range(2):
        if i == 0:
            axs[i, j].pcolorfast(x_edges, y_edges, data, cmap='Grays', interpolation='nearest')
            axs[i, j].set_title('PcolorImage')
        else:
            im = NonUniformImage(axs[i, j], interpolation='nearest', cmap='Grays')
            im.set_data(x_mids, y_mids, data)
            axs[i, j].add_image(im)
            axs[i, j].set_title('NonUniformImage')

        axs[i, j].set_aspect('equal')
        axs[i, j].set_axis_off()
        axs[i, j].vlines(seps, -1, N[j] + 1, lw=0.5, color='red', ls='dashed')
        axs[i, j].hlines(seps, -1, N[j] + 1, lw=0.5, color='red', ls='dashed')

        box = Rectangle((0.5, 1.5), 2, 2, edgecolor='yellow', facecolor='none', lw=1)
        axs[i, j].add_artist(box)

plt.show()
```

**Comment by ayshih** [comment]
Edit: I'll keep this post around for posterity, but there is now [a better fix](https://github.com/matplotlib/matplotlib/pull/31021#issuecomment-3843329521) that doesn't have the downside described here.

---
Original post:

This PR now also (partially) fixes a subtle bug with RGBA resampling of an image under affine transform and non-nearest-neighbor interpolation.  #29776 changed the RGBA resampling to premultiply the alpha channel before resampling, and then divide the resampled alpha channel afterwards.  This approach makes sense where the resampled alpha channel is solely an interpolation of the original alpha channel.

However, the resampled alpha channel *also* has alpha variations at the image edges due to the rendering box, even when the original alpha channel is constant.  The alpha channel is used to fade the edges while the color is unchanged.  So, the post-resampling step of dividing by the alpha channel is incorrect because the color is not in premultiplied alpha space.  This causes the edge to be enhanced and potentially shift in color as color channels saturate.

### Before this PR
before

Fully fixing this bug is a tricky due to the mix of how the alpha channel can be constructed.  This PR implements a (partial) fix of not working in premultiplied alpha space if the original alpha channel is constant.  Thus, at least in those cases, which includes the very common case of no specified alpha channel, the edges will appear clean as they are supposed to.  A full fix is deferred to future work.

### After this PR
after

### Generating code
```python
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.transforms import Affine2D

np.random.seed(19680801+9)  # need this seed to get yellow next to blue
data = np.random.rand(4, 4)

rotation = Affine2D().rotate_around(1.5, 1.5, 1)

fig, axs = plt.subplots(1, 2)

for i in range(2):
    transform = axs[i].transData
    if i != 0:
        transform = rotation + transform

    axs[i].imshow(data, interpolation='bilinear', interpolation_stage='rgba', transform=transform)
    axs[i].set_xlim(-2, 5)
    axs[i].set_ylim(-2, 5)

plt.show()
```

**Comment by ayshih** [comment]
This PR is now ready for review!  Sorry that it updates so many baseline images, but I do not think that it is appropriate to simply increase the tolerances.  These improvements are truly necessary and should be stringently tested.  I also added a changelog entry because this will break most image-comparison tests in other packages (e.g., Astropy and SunPy).

In addition to the above examples, some baseline images also clearly show the improvements.  For example:
* [test_axes/use_colorizer_keyword.png](https://github.com/matplotlib/matplotlib/pull/31021/changes#diff-01e6a17d0370114ff80d19618cb7e242520fe66e13160d6f88b661358bb0d969), central panels
* [test_constrainedlayout/test_colorbars_no_overlapH.png](https://github.com/matplotlib/matplotlib/pull/31021/changes#diff-0a2216b3371f868b8ae8996b435a15c5bd046e705b7a1a7c1c57396980c37c81)

The only arguable downside to these changes is that rendered PDF/SVG output at very low image DPI can look worse because the rendered axes are not at that same low DPI.  That is, the low-DPI image will not be nicely placed relative to the high-DPI axes.  However, I think these very low DPIs are not realistic use cases, but rather an artificial choice for testing purposes.  For example:
* [test_image/interp_nearest_vs_none.svg‎](https://github.com/matplotlib/matplotlib/pull/31021/changes#diff-e6b43e8d7f7ce809e0354f914d18a80d1f63b0372ed02587fc505ceaccf741f9), 3 DPI

I'll hop on an upcoming dev meeting to facilitate the review of this PR.

**Comment by scottshambaugh** [comment]
Looking through the comparison images, things by-and-large look way better. Here's where I see some things to check:

* `downsampling.png` seems to have large differences on the left side - is that expected?
* The behavior for `interp_nearest_vs_none.svg` looks worse
* In the right colorbar in `mask_image_over_under.png`, the color bands don't line up exactly with the ticks. No worse than before, but potentially related to what you're looking at?
* In the bottom-right plot for `rgba_antialias.png`, the right edge looks worse
* In `rotate_image.png`, it looks like we lost anti-aliasing
* In `pngsuite.png`, it looks like we opened some gaps between the square sections
* For `image_bounds_handling.png`, please add some comments in the test saying that the two bottom right images are not as expected right now and will need to be updated when that handling is fixed

**Comment by ayshih** [comment]
Thanks for looking closely at the changed baseline images!

> * `downsampling.png` seems to have large differences on the left side - is that expected?

Yes. essentially.  The image array is significantly downsampled and varies every other row on the left side, so there is severe aliasing when using nearest-neighbor interpolation.  The small changes that this PR does to the sampling locations gets amplified by the severe aliasing.  The bottom row shows non-nearest-neighbor interpolation, hence the lack of the aliasing effect.

> * The behavior for `interp_nearest_vs_none.svg` looks worse

Yup, that's what I described in my previous post.  I would argue that requesting an image at 3 DPI in a PDF/SVG is not a realistic use case.

> * In the right colorbar in `mask_image_over_under.png`, the color bands don't line up exactly with the ticks. No worse than before, but potentially related to what you're looking at?

I believe that the color bands are lined up with the ticks as well as possible, given nearest-neighbor interpolation.  A tick mark's position is rounded to the nearest output pixel, so it can't fall exactly on the sharp separation between two color bands.

> * In the bottom-right plot for `rgba_antialias.png`, the right edge looks worse

Ah, good catch!  I suspect that I simply need to update the baseline image to the latest, and I missed it because of the tolerance on that test.

> * In `rotate_image.png`, it looks like we lost anti-aliasing

Yes, that is true.  To recap, the way that affine-transform nearest-neighbor plotting works before this PR is that the image is enlarged slightly bigger than it should be, antialiased at the edges, and then placed slightly inaccurately in the output.  The plus side is that the image looks like it fills an axes box completely while also having a nice antialiased edge when there is no border.  The minus side is that the image pixels are slightly bigger than they should be, and the edge pixels are a bit shortchanged because they either get slightly hidden by the border or slightly faded by the antialiasing.

This PR takes the stance of plotting nearest-neighbor exactly correctly, but that also means that it's not possible to have an antialiased edge.  If the edge is faded at all for antialiasing, the image will no longer fill an axes box completely.

> * In `pngsuite.png`, it looks like we opened some gaps between the square sections

Stay tuned

> * For `image_bounds_handling.png`, please add some comments in the test saying that the two bottom right images are not as expected right now and will need to be updated when that handling is fixed

Yup, I'll do that.  That said, I'm not optimistic that it can ever be solved for arbitrary input.

**Comment by scottshambaugh** [comment]
These all make sense to me, thanks for going through them!

> This PR takes the stance of plotting nearest-neighbor exactly correctly, but that also means that it's not possible to have an antialiased edge. If the edge is faded at all for antialiasing, the image will no longer fill an axes box completely.

I agree with this tradeoff. In practice, most of our edges are vertical/horizontal and won't be affected.

**Comment by scottshambaugh** [comment]
It does seem like your CI failures are real, btw

**Comment by ayshih** [comment]
(There was [an earlier partial fix](https://github.com/matplotlib/matplotlib/pull/31021#issuecomment-3827514385), but now the following bug is fixed properly.  The incompleteness of the earlier fix is the reason for the strange colors at the right side of `rgba_antialias.png`.)

This PR now also fixes a subtle bug with RGBA resampling of an image under affine transform and non-nearest-neighbor interpolation.  #29776 changed the RGBA resampling to premultiply the alpha channel before passing the image to Agg, and then divide the resampled alpha channel afterwards.  However, the code continued to use the Agg blender that assumes the image is in non-premultiplied space, so the Agg blender multiplied the alpha channel in again, antialiased the edge, and then demultiplied the alpha channel.  This inconsistent premultiplying causes the resulting alpha of the antialiased edge to be incorrect, and also potentially to shift in color as color channels saturate.

The proper fix is to simply switch to the Agg blender that is for an image that is already in premultiplied space.  The antialiased edge now looks correct.

### Before this PR
before

### After this PR
after

### Generating code
```python
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.transforms import Affine2D

np.random.seed(19680801+9)  # need this seed to get yellow next to blue
data = np.random.rand(8, 8)

rotation = Affine2D().rotate_around(3.5, 3.5, 1)

fig, axs = plt.subplots(1, 2)

axs[0].imshow(data, interpolation='bilinear', interpolation_stage='rgba', transform=rotation + axs[0].transData)
axs[0].set_title('Uniform alpha')
axs[0].set_xlim(-2.5, 9.5)
axs[0].set_ylim(-2.5, 9.5)

data[2:4, 2:4] = np.nan
axs[1].imshow(data, interpolation='bilinear', interpolation_stage='rgba', transform=rotation + axs[1].transData)
axs[1].set_title('Nonuniform alpha')
axs[1].set_xlim(-2.5, 9.5)
axs[1].set_ylim(-2.5, 9.5)

plt.show()
```

**Comment by ayshih** [comment]
I fixed the remaining issues, so this PR is ready for review again!  There should no longer fading or gaps at the end of images when they are expected to touch the axes or an adjacent image.

File: src/_image_resample.h [hunk 1]
```diff
@@ -755,14 +758,35 @@ void resample(
...
+	    if (round(left) < left) left = round(left);
+	    if (round(right) > right) right = round(right);
+	    if (round(bottom) < bottom) bottom = round(bottom);
+	    if (round(top) > top) top = round(top);
+            path.move_to(left, bottom);
+            path.line_to(right, bottom);
+            path.line_to(right, top);
+            path.line_to(left, top);
+            path.close_polygon();
+            rasterizer.add_path(path);
```
Comment (scottshambaugh) [inline src/_image_resample.h]: There are some tabs mixed in with the spaces here

File: src/_image_resample.h [hunk 2]
```diff
@@ -755,14 +758,35 @@ void resample(
...
+        } else {
+            // If there is no shear/rotation, bump out the rendering edges that are
+	    // within a half pixel of a full pixel so that axes are visually filled
+	    double left = 0;
+	    double right = in_width;
+	    double bottom = 0;
+	    double top = in_height;
+	    params.affine.transform(&left, &bottom);
+	    params.affine.transform(&right, &top);
+	    if (round(left) < left) left = round(left);
```
Comment (scottshambaugh) [inline src/_image_resample.h]: Claude suggests that for images with `origin="upper"` you'll want to flip the bounds before rounding. I don't believe the current test images cover that case.

```suggestion
        if (left > right) std::swap(left, right);
        if (bottom > top) std::swap(bottom, top);
        if (round(left) < left) left = round(left);
```

File: doc/api/next_api_changes/behavior/31021-AYS.rst [hunk 3]
```diff
@@ -0,0 +1,7 @@
+Rendering of images now more accurate
+~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+There have been a bunch of fixes to improve the accuracy of how images are
```
Comment (QuLogic) [inline doc/api/next_api_changes/behavior/31021-AYS.rst]:
```suggestion
There have been several fixes to improve the accuracy of how images are
```

File: lib/matplotlib/tests/baseline_images/test_image/downsampling.png
Comment (QuLogic) [inline lib/matplotlib/tests/baseline_images/test_image/downsampling.png:1]: Is it really true that there are 10 bars on the left of the Axes instead of 8 now?

File: src/_image_resample.h [hunk 4]
```diff
@@ -511,7 +511,7 @@ struct type_mapping
         std::conditional_t<
             std::is_same_v<color_type, agg::rgba8>,
             fixed_blender_rgba_plain<color_type, agg::order_rgba>,
-            agg::blender_rgba_plain<color_type, agg::order_rgba>
+            agg::blender_rgba_pre<color_type, agg::order_rgba>
```
Comment (QuLogic) [inline src/_image_resample.h:514]: We don't normally work in premultiplied space. Does this just happen to work out to the same thing as plain->plain blending, just with a more precise algorithm? If so, would it make sense to instead extend our "fixed" version above to work with more data widths?

I'm not sure there are tests for images blending onto transparency or not, to check whether this works right when it's not to an opaque background.

**Review by QuLogic — COMMENTED** [review]
Haven't looked to detailed, just some quick comments.

File: src/_image_resample.h (hunk 2 above)
Comment (ayshih) [reply src/_image_resample.h]: Oh, interesting!  That's probably needed.  I have to jazz up that new figure test anyway because the solid Axes spines obscure two of the edges, so I'll confirm.

File: src/_image_resample.h (hunk 1 above)
Comment (ayshih) [reply src/_image_resample.h]: Whoops, thanks!

File: lib/matplotlib/tests/baseline_images/test_image/downsampling.png
Comment (ayshih) [reply lib/matplotlib/tests/baseline_images/test_image/downsampling.png:1]: See https://github.com/matplotlib/matplotlib/pull/31021#issuecomment-3838678379 for my explanation.  The severe aliasing changes appearance because the downsampling is both shifted and spaced differently (because of the removal of the enlarging step), so the number of bars is not particularly important.

File: src/_image_resample.h (hunk 4 above)
Comment (ayshih) [reply src/_image_resample.h:514]: (See also https://github.com/matplotlib/matplotlib/pull/31021#issuecomment-3843329521)

#29776 changed things so that RGBA images are always converted to floats and have alpha premiltiplied before being passed to the Agg resampler.  That makes sure the interpolation step handles colors correctly.  However, that PR did not tell Agg that the image was premultiplied, so the subsequent step of antialiasing the edges is not done correctly.  That is, the Agg output was such that the image was premultiplied inside the image and plain at its edges.  So, the external demultiplying afterwards would screw up the edges because it was demultiplying something that was already plain.

#29776 did not touch `interpolation_stage='data'` interpolation, and it also made the 8-bit RGBA logic path no longer used.

I can enhance `rgba_clean_edges.png` to test the transparency.

File: doc/api/next_api_changes/behavior/31021-AYS.rst (hunk 3 above)
Comment (ayshih) [reply doc/api/next_api_changes/behavior/31021-AYS.rst]: Done

File: src/_image_resample.h (hunk 2 above)
Comment (ayshih) [reply src/_image_resample.h]: By "that new figure test", I was referring to a test that I had forgotten to include.  There's now a figure test that tests this code for combinations of `origin` and mirror flips: [affine_fill_to_edges.png‎](https://github.com/matplotlib/matplotlib/pull/31021/changes#diff-88e6c31a32b94c931d5299cd7829f456c14b2e2283ffe16985735eaaf04e8bdc)

File: src/_image_resample.h (hunk 4 above)
Comment (ayshih) [reply src/_image_resample.h:514]: [rgba_clean_edges.png‎](https://github.com/matplotlib/matplotlib/pull/31021/changes#diff-1065963b6b62507203d861986414180a6f9843a8bf0cb211b037d352225e5aef) now has several patches under the antialiased edge so that it's easier to see the quality of the antialiased edge.  I'll point out that the bug being fixed here is not affected by the color or alpha of the background below the image: `make_image()` provides a background of no color/alpha to the Agg resampler in order to get clean edges.  The later rendering of the image over whatever background has no interpolation and is not bugged.

File: src/agg_workaround.h [hunk 5]
```diff
@@ -42,4 +43,87 @@ struct fixed_blender_rgba_plain : agg::conv_rgba_plain<ColorT, Order>
...
+    {
+        subpixel_shift = SubpixelShift,
+        subpixel_scale  = 1 << subpixel_shift
+    };
+
+    //--------------------------------------------------------------------
+    accurate_interpolator_affine_nn() {}
+    accurate_interpolator_affine_nn(trans_type& trans) : m_trans(&trans) {}
+    accurate_interpolator_affine_nn(trans_type& trans,
+                             double x, double y, unsigned len) :
```
Comment (QuLogic) [inline src/agg_workaround.h]: Minor nit: this is misaligned.

File: src/_image_resample.h [hunk 6]
```diff
@@ -759,13 +759,36 @@ void resample(
...
+            double bottom = 0;
+            double top = in_height;
+            params.affine.transform(&left, &bottom);
+            params.affine.transform(&right, &top);
+            if (left > right) std::swap(left, right);
+            if (bottom > top) std::swap(top, bottom);
+            if (round(left) < left) left = round(left);
+            if (round(right) > right) right = round(right);
+            if (round(bottom) < bottom) bottom = round(bottom);
+            if (round(top) > top) top = round(top);
```
Comment (QuLogic) [inline src/_image_resample.h]: PEP7 says always use braces.

File: src/_image_resample.h [hunk 7]
```diff
@@ -755,14 +758,37 @@ void resample(
...
```
Comment (tacaswell) [inline src/_image_resample.h]:
```suggestion
            if (left > right) { std::swap(left, right); }
            if (bottom > top) { std::swap(top, bottom); }
            if (round(left) < left) { left = round(left); }
            if (round(right) > right) { right = round(right); }
            if (round(bottom) < bottom) { bottom = round(bottom); }
            if (round(top) > top) { top = round(top); }
```

PEP7 says always use braces.  It also says we should push all of these up to 3 lines, but I think that it is clearer in one line like this.  Will defer to anyone who has a strong opinion.

File: lib/matplotlib/tests/test_image.py [hunk 8]
```diff
@@ -1871,3 +1878,57 @@ def test_interpolation_stage_rgba_respects_alpha_param(fig_test, fig_ref, intp_s
...
     )
+
+
+@image_comparison(['nn_pixel_alignment.png'])
+def test_nn_pixel_alignment(nonaffine_identity):
+    fig, axs = plt.subplots(2, 3)
+
+    N = [3, 7, 11]
+
+    for j in range(3):
```
Comment (QuLogic) [inline lib/matplotlib/tests/test_image.py]:
```suggestion
    for j, N in enumerate([3, 7, 11]):
```

File: lib/matplotlib/tests/test_image.py [hunk 9]
```diff
@@ -1871,3 +1878,57 @@ def test_interpolation_stage_rgba_respects_alpha_param(fig_test, fig_ref, intp_s
...
+
+@image_comparison(['image_bounds_handling.png'], tol=0.006)
+def test_image_bounds_handling(nonaffine_identity):
+    fig, axs = plt.subplots(2, 3)
+
+    N = 11
+
+    interpolation = ['nearest', 'hanning', 'bilinear']
+
+    for j in range(3):
```
Comment (QuLogic) [inline lib/matplotlib/tests/test_image.py]:
```suggestion
    for j, interpolation in enumerate(['nearest', 'hanning', 'bilinear']):
```

**Review by QuLogic — COMMENTED** [review]
Some minor nits, but also a small ask: please add a bit more context to the commit messages; it is helpful to find out the why of a change without having to search out the PR. Maybe not the entirety of the test images you have here, but at least more than the single-line messages.

File: src/_image_resample.h (hunk 7 above)
Comment (ayshih) [reply src/_image_resample.h]: Done

File: src/agg_workaround.h (hunk 5 above)
Comment (ayshih) [reply src/agg_workaround.h]: Fixed

File: lib/matplotlib/tests/test_image.py (hunk 8 above)
Comment (ayshih) [reply lib/matplotlib/tests/test_image.py]: Ah, of course

**Comment by ayshih** [comment]
> please add a bit more context to the commit messages; it is helpful to find out the why of a change without having to search out the PR.

Sure, I've added a bunch of sentences to the commit messages

**Comment by QuLogic** [comment]
I'd like to keep the individual commits, so please squash the fixups into the originals. I assume that a lot of the commits affect test images repeatedly, so it's probably fine to keep those updates in a single separate commit.

**Comment by ayshih** [comment]
Sure, I've squashed the commits down to nine commits
