### PR TITLE
PRF: Speed up point_in_path and friends

### LINKED ISSUE #6444: matplotlib.path.contains_points is a LOT slower in 1.51
Hi!

I have a code using matplotlib.path to create a mask of points inside a polygon. Lately we moved from version 1.4 to 1.51 and at first I thought that our program started to hang but it turned out that it just took about 30x more time to create masks.

Profiler showed that the problem is with path.contains_points(pts).
I've extracted the problem to a unit test and did tests 1.4 vs 1.51:
1.4 - 70 ms
1.51 - 2215 ms

    import unittest
    import numpy as np
    import math

    import matplotlib
    from matplotlib.path import Path

    print matplotlib.__version__

    class MyTestCase(unittest.TestCase):
        def get_polygon_path(self, polygon_x, polygon_y):
            vertices = zip(polygon_x, polygon_y)
            p = Path(vertices, None, closed=True, readonly=True)
            return p

        def get_in_polygon(self, x1, x2, y1, y2, path):
            x, y = np.meshgrid(np.arange(x1, x2), np.arange(y1, y2))
            x, y = x.flatten(), y.flatten()
            pts = np.vstack((x, y)).T

            # Find points that belong to snake in minimal rectangle
            grid = path.contains_points(pts)

        def test_matplotlib(self):
            for k in range(10):
                angles = np.linspace(0, 2 * math.pi, 90)
                px = 150 + 100 * np.cos(angles)
                py = 150 + 100 * np.sin(angles)

                poly = self.get_polygon_path(px, py)
                self.get_in_polygon(50, 250, 50, 250, poly)

            self.assertEqual(True, True)

    if __name__ == '__main__':
        unittest.main()

Am I doing or setting something wrong or is it indeed a problem with a new version?

Regards
Filip Mróz

### PR DESCRIPTION
**Pull request by mdboom**
This is an alternative to #6446. Fix #6444.

- Moves to using (, ) instead of [] for indexing in `point_in_path_impl` which avoids Python ref/deref and is therefore much faster
- Renames `operator[]` to subarray (which is still useful in some places where speed is less critical) and moves to using (, ,) elsewhere in the codebase where it makes sense.
- Reverts the use of `bool` for the results in `point_in_path_impl`, which strangely was a lot slower
- Doesn't use the contouring algorithm unless the radius is nonzero.  This is a large performance win and brings us under 1.4.3 times in the common case.

### CODE REVIEW

**Comment by mdboom** [comment]
Thanks to @tacaswell and @QuLogic for the legwork on this one!

File: src/_backend_agg.h [hunk 1]
```diff
@@ -961,13 +961,13 @@ inline void RendererAgg::_draw_path_collection_generic(GCAgg &gc,
...
 
         if (Ntransforms) {
-            typename TransformArray::sub_t subtrans = transforms[i % Ntransforms];
-            trans = agg::trans_affine(subtrans(0, 0),
-                                      subtrans(1, 0),
-                                      subtrans(0, 1),
-                                      subtrans(1, 1),
-                                      subtrans(0, 2),
-                                      subtrans(1, 2));
+            int it = i % Ntransforms;
```
Comment (WeatherGod) [inline src/_backend_agg.h]: here you are using `int`'s, but elsewhere, you use `size_t`. Any particular reason for that?

**Comment by WeatherGod** [comment]
I am also perplexed about the performance issues with bool vs. uint8_t. Perhaps we should mention it to the numpy folks to see if they have any insights? That is the only change that has me a bit uneasy. Other than that, this looks good to me.

**Comment by tacaswell** [comment]
If I recall correctly stl special cases bool and implements it as a
bitfield on top of a vector of ints.  I bet the translation layer in there
where the extra cost is.

As this is stl I do not think numpy would have any input (as I thought they
were all c).

Tom

**Comment by dopplershift** [comment]
@tacaswell I remembered something similar to you about `std::vector<bool>`, and we're correct: http://en.cppreference.com/w/cpp/container/vector_bool

Notes from there:

1. `vector<bool>` is not necessarily contiguous in memory (WTF???)
2. `vector<bool>` packs bits together.

So, going back to vector<int> should be much better.
