### PR TITLE
nbagg: Don't close figures for bubbled events.

### LINKED ISSUE #18638: `matplotlib>=3.3.2` breaks `ipywidgets.interact`
### Bug report

**Bug summary**

Using `ipywidgets.interact` to update a figure works as expected in `matplotlib<=3.3.1`, but fails in `matplotlib==3.3.2`.

I don't think this is an `ipywidgets` issue since downgrading `matplotlib` fixes this issue.

**Code for reproduction**

In[1]:
```python
%matplotlib notebook
import matplotlib as mpl
import matplotlib.pyplot as plt
import ipywidgets as ipyw
"works if %s <= 3.3.1" % mpl.__version__
```
In[2]:
```python
fig = plt.figure()
@ipyw.interact(m=ipyw.FloatSlider(value=1, min=-10, max=10, step=0.01))
def update(m):
    plt.figure(fig.number, clear=True)
    plt.plot([m * x for x in range(-9, 10)])
```

Followed by moving the slider.

**Actual outcome**

- when moving the slider, the figure does not update
- a second figure is sometimes created instead
- the second figure is usually blank, but sometimes updates instead

**Expected outcome**

- the original figure updates as it does in `matplotlib==3.3.1`

**Matplotlib version**

  * Operating system: Ubuntu
  * Matplotlib version: 3.3.2 vs 3.3.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): nbAgg
  * Python version: 3.7.8
  * Jupyter version (if applicable): jupyter-core==4.6.3
  * Other libraries: ipywidgets==7.5.1
  * Installation source: `conda` channel `conda-forge`

### PR DESCRIPTION
**Pull request by QuLogic**
## PR Summary

In JavaScript, the event handlers are called for both the element and also bubbled up from any children. If the Matplotlib figure is the only thing in the output, that's fine, as closing the figure when one of the `canvas` or `div`s clears is the same as when the `OutputArea` is cleared. However, if there are other outputs, such as widgets, we do not want to close the figure if one of them is cleared.

As there's no way to clear just the figure output, only close the figure if the _entire_ `OutputArea` div is cleared (i.e., the element we've attached to).

Fixes #18638.

## PR Checklist

- [ ] Has pytest style unit tests (and `pytest` passes).
- [x] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [n/a] New features are documented, with examples if plot related.
- [n/a] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [x] Conforms to Matplotlib style conventions (install `flake8-docstrings` and `pydocstyle<4` and run `flake8 --docstring-convention=all`).
- [n/a] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [n/a] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

### CODE REVIEW

File: lib/matplotlib/backends/web_backend/js/nbagg_mpl.js [hunk 1]
```diff
@@ -48,7 +48,7 @@ mpl.mpl_figure_comm = function (comm, msg) {
         console.error('Failed to find cell for figure', id, fig);
         return;
     }
-    fig.cell_info[0].output_area.element.one(
+    fig.cell_info[0].output_area.element.on(
```
Comment (QuLogic) [inline lib/matplotlib/backends/web_backend/js/nbagg_mpl.js:51]: Note, since we are now ignoring some events, we can't just attach on the first trigger (`.one`), but all of them (`.on`)

**Review by timhoffm — APPROVED** [review]

**Review by dopplershift — APPROVED** [review]

**Comment by dopplershift** [comment]
Travis passed, status just didn't update.
