### PR TITLE
Check dimensions of arrays passed to C++, handle 0 dimensions

### LINKED ISSUE #5185: Random test failures in Legent tests (1.5.0rc2)
On my 10.11 OSX machine I am seeing random failures in legent tests such as

```
======================================================================
FAIL: matplotlib.tests.test_legend.test_various_labels.test
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/testing/decorators.py", line 53, in failer
    result = f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/testing/decorators.py", line 220, in do_test
    '(RMS %(rms).3f)'%err)
ImageComparisonFailure: images not close: /Users/jhn/src/python/matplotlib/result_images/test_legend/legend_various_labels.png vs. /Users/jhn/src/python/matplotlib/result_images/test_legend/legend_various_labels-expected.png (RMS 13.877)
```

legend_various_labels

This happens randomly for various of the tests with both python 2 and 3. I seem to be able to reproduce it outside the test suite so I don't think it is related to race conditions in the test code.

### PR DESCRIPTION
**Pull request by mdboom**
This is a combination of #5264 and #5246 that doesn't require #5241, and thus should be more robust to unusual arrays that Numpy creates with 0 dimensions in the middle somewhere.

Fixes #5185

### CODE REVIEW

**Comment by cimarronm** [comment]
:+1:

File: src/_path.h [hunk 1]
```diff
@@ -358,7 +358,7 @@ void get_path_collection_extents(agg::trans_affine &master_transform,
                                  agg::trans_affine &offset_trans,
                                  extent_limits &extent)
 {
-    if (offsets.dim(0) != 0 && offsets.dim(1) != 2) {
+    if (offsets.size() != 0 && offsets.dim(1) != 2) {
```
Comment (jkseppan) [inline src/_path.h]: I'm not sure if this needed changing, but it doesn't hurt aside from a vague feeling of asymmetry.

**Comment by jkseppan** [comment]
:+1:

Should there be a note in the documentation recommending the use of `size()` instead of `dim(0)`?

**Comment by mdboom** [comment]
I've added a comment about size().  We don't really have formal documentation about our internal C++ APIs outside of header comments.

**Comment by mdboom** [comment]
Backported to 1.5.x as f52932714
