### PR TITLE
Use both TCL_SETVAR and TCL_SETVAR2 for tcl 9 support

### LINKED ISSUE #29126: [Bug]: TkAgg backend is broken with tcl/tk 9.0
### Bug summary

When trying to use TkAgg backend with tkinter compiled with tcl/tk 9.0(ex. `python-tk` with Python 3.13 from Homebrew), the backend fails to load

### Code for reproduction

```Python
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg
```

### Actual outcome

```
    from . import _tkagg
ImportError: Failed to load Tcl_SetVar
```

### Expected outcome

works as expected

### Additional information

`Tcl_SetVar` function is removed in tcl 9.0, which is used in `DpiSubclassProc` of `src/_tkagg.cpp` on Windows. The function can easily be replaced with `Tcl_SetVar2` if exists.

### Operating system

macOS 14.6

### Matplotlib Version

3.9.2

### Matplotlib Backend

_No response_

### Python version

3.13

### Jupyter version

_No response_

### Installation

pip

### PR DESCRIPTION
**Pull request by ksunden**
Provides both the older and newer APIs for compatibility with both tcl 9 plus and older versions.

Co-authored-by: Antony Lee <anntzer.lee@gmail.com>

Closes #29126 

## PR checklist

- [x] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [x] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [x] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/document.html#write-examples-and-tutorials)
- [x] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/api_changes.html#announce-changes-deprecations-and-new-features)
- [x] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/document.html#write-docstrings) guidelines

### CODE REVIEW

File: src/_tkagg.cpp [hunk 1]
```diff
@@ -343,8 +355,8 @@ PYBIND11_MODULE(_tkagg, m, py::mod_gil_not_used())
         throw py::error_already_set();
     }
 
-    if (!TCL_SETVAR) {
-        throw py::import_error("Failed to load Tcl_SetVar");
+    if (!(TCL_SETVAR || TCL_SETVAR2)) {
+        throw py::import_error("Failed to load Tcl_SetVar and Tcl_SetVar2");
```
Comment (tacaswell) [inline src/_tkagg.cpp:359]:
```suggestion
        throw py::import_error("Failed to load Tcl_SetVar or Tcl_SetVar2");
```

**Review by tacaswell — APPROVED** [review]

**Comment by tacaswell** [comment]
As this is a patch from @anntzer added by @ksunden and reviewed by me I think this has enough review and can be merged by anyone on green.
