### PR TITLE
Replace ttconv by plain python for pdf subsetting

### LINKED ISSUE #17197: Missing character upon savefig() with Free Serif font
### Bug report

**Bug summary**

Choosing the font "Free Serif".

Right parenthesis character ")" is not printed upon using fig.savefig().

It is correctly printed upon using plt.show().

**Code for reproduction**

```python
import matplotlib.pyplot as plt
fig, ax = plt.subplots()
ax.text(s='(Some text)', x=0.5, y=0.5, fontname='freeserif')
fig.savefig('fig.pdf')
```

**Actual outcome**

Right parenthesis is not printed on pdf.

**Expected outcome**

All characters should be printed on pdf.

**Matplotlib version**

  * Operating system: Fedora 31 Workstation
  * Matplotlib version:  3.2.1
  * Python version: 3.7.6

### PR DESCRIPTION
**Pull request by anntzer**
## First commit:

Switch from a hand-written glyph outline decomposer to FreeType's one.

Instead of walking through FT_Outline ourselves, use FreeType's
FT_Outline_Decompose to decompose glyphs into paths.

Fixes incorrect positioning of first and last control points of certain
contours; compare e.g.
```python
from pylab import *
from matplotlib.textpath import TextPath
from matplotlib.patches import PathPatch

rcParams["mathtext.fontset"] = "stixsans"
path = TextPath((0, 0), r"$\delta$", size=72)
plot(*path.vertices.T, ".-", lw=.5)
gca().add_patch(PathPatch(path, alpha=.5))
gca().set(aspect="equal")
show()
```
before and after the patch (before the patch, the inner loop was not
properly closed).  (Technically, I believe the earlier bug affected
start/end-of-contours that are implicitly created per the ttf format at
the midpoint between two conic control points.)

before:
old

after:
new

A few SVG files need to be updated too.

## Second commit:

Stop using ttconv for pdf.

Quite a bit of work goes into reproducing quirks of the old ttconv code
in order not to update baseline images, but this can easily be dropped
once the new baseline images system goes in.

figure_align_label.pdf gets modified because of tiny differences in
outline extraction (due to the ttconv emulation); there's already the
svg test that tests the fixed-dpi case so I feel OK deleting it.

This also fixes ttc subsetting for pdf output (cf. changes in
test_font_manager.py).

-----

(PostScript is not done yet, but it's basically the same idea, it's just the header that's different.)

Fixes #17197.  I'll skip adding a new font for the test, because in essence we're "just" relying on FreeType handing us the right outlines.

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/next_api_changes/* if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by QuLogic** [comment]
> Instead of walking through FT_Outline ourselves, use FreeType's
> FT_Outline_Decompose to decompose glyphs into paths.

Cool, I wanted to do that, except for it breaking images, like you've found.

File: src/ft2font.cpp [hunk 1]
```diff
@@ -188,325 +189,126 @@ static FT_UInt ft_get_char_index_or_warn(FT_Face face, FT_ULong charcode)
...
-                *(outpoints++) = yctl;
-                *(outpoints++) = xto;
-                *(outpoints++) = yto;
-                *(outcodes++) = CURVE3;
-                *(outcodes++) = CURVE3;
-
-                goto Close;
-            }
+static int ft_outline_cubic_to(
+  FT_Vector const* control1, FT_Vector const* control2, FT_Vector const* to, void* user)
```
Comment (QuLogic) [inline src/ft2font.cpp:254]:
```suggestion
static int
ft_outline_cubic_to(FT_Vector const* control1, FT_Vector const* control2, FT_Vector const* to, void* user)
```
(Might need to wrap at 80)

File: src/_path.h [hunk 2]
```diff
@@ -1089,35 +1089,39 @@ void quad2cubic(double x0, double y0,
...
-    ++q;
-    *q = 0;
-
-    try {
-        buffer += str;
-    } catch (std::bad_alloc& e) {
+        // Rewind through all the zeros
+        while (q >= str && *q == '0') { --q; }
+        // If the end is a decimal point, delete that too
+        if (q >= str && *q == '.') { --q; }
```
Comment (QuLogic) [inline src/_path.h:1113]: Stylistically, this might be against PEP7.

File: src/ft2font.cpp [hunk 3]
```diff
@@ -188,325 +189,126 @@ static FT_UInt ft_get_char_index_or_warn(FT_Face face, FT_ULong charcode)
...
-
-                count += 3;
-
-                goto Count_Close;
-            }
-            }
+static int ft_outline_move_to(
+  FT_Vector const* to, void* user)
+{
+    ft_outline_decomposer* d = reinterpret_cast<ft_outline_decomposer*>(user);
```
[the remark this answers is not in the document]
Comment (anntzer) [reply src/ft2font.cpp]: yes throughout, except for the last point

File: src/_path.h (hunk 2 above)
Comment (anntzer) [reply src/_path.h:1113]: I know, but I think splitting things on their own lines (as was done before) makes the code really harder to follow because the information density is so low...

Comment (anntzer) [reply src/_path.h]: I went for a slight variation which does respect pep7.

File: src/_path.h [hunk 4]
```diff
@@ -1089,35 +1089,38 @@ void quad2cubic(double x0, double y0,
...
+        // Rewind through all the zeros and, if present, the trailing decimal
+        // point.  Py_DTSF_ADD_DOT_0 ensures we won't go past the start of str.
+        while (*c == '0') {
+            --c;
+        }
+        if (*c == '.') {
+            --c;
+        }
+        try {
+            buffer.append(str, c + 1);
```
Comment (QuLogic) [inline src/_path.h:1117]: Second parameter is size, isn't it?
```suggestion
            buffer.append(str, c - str + 1);
```

File: lib/matplotlib/backends/backend_pdf.py [hunk 5]
```diff
@@ -556,6 +555,52 @@ def _flush(self):
...
+        # the quad before and the quad after, but ttconv used to interpolate
+        # *after* conversion to PS units, causing floating point errors.  Here
+        # we reproduce ttconv's logic, detecting these "implicit" points and
+        # re-interpolating them.  Note that occasionally (e.g. with DejaVu Sans
+        # glyph "0") a point detected as "implicit" is actually explicit, and
+        # will thus be shifted by 1.
+        quads, = np.nonzero(c == 3)
+        quads_on = quads[1::2]
+        quads_mid_on = np.array(
+            sorted({*quads_on} & {*quads - 1} & {*quads + 1}), int)
```
Comment (QuLogic) [inline lib/matplotlib/backends/backend_pdf.py:581]: The spacing makes the precedence a bit unclear:
```suggestion
            sorted({*quads_on} & {*(quads - 1)} & {*(quads + 1)}), int)
```

File: src/_path.h (hunk 4 above)
Comment (anntzer) [reply src/_path.h:1117]: This is using the
```
template< class InputIt >
basic_string& append( InputIt first, InputIt last );
```
overload, not the
```
basic_string& append( const CharT* s, size_type count );
```
one.

File: lib/matplotlib/backends/backend_pdf.py (hunk 5 above)
Comment (anntzer) [reply lib/matplotlib/backends/backend_pdf.py:581]: sure

**Comment by anntzer** [comment]
One thing I forgot to mention is that the Py_DTSF_ADD_DOT_0 change also fixes a separate bug in `__add_number`, whereby passing `precision = 0` would previously print values without the dot and then trailing but significant zeros would be incorrectly stripped out.  This doesn't affect the patch here because this uses the separate bug-compat precision=-1 path, but the (future) backend_ps patch will use precision=0 and thus benefit from this.

**Comment by QuLogic** [comment]
Should we wait for the baseline image PR before merging this?

**Comment by anntzer** [comment]
I put in all the bug-compat code explicitly to minimize the image diffs; I'd say the remaining svg diffs are not *too* large, but I'm not in a big hurry either.

**Comment by jklymak** [comment]
I'll merge since @anntzer is the main person concerned with images changing 😉
