### PR TITLE
Convert Qhull wrapper to C++ and array_view

### LINKED ISSUE #19627: Replace use of Python/C API with numpy::array_view in _tri.cpp and qhull_wrap.c
`_tri.cpp` and `qhull_wrap.c` use the Python/C API to create numpy arrays, e.g.:

https://github.com/matplotlib/matplotlib/blob/bc972942bd41a32c7cd693a3f29a29442d2d6e3f/src/tri/_tri.cpp#L638-L639

It would be better to use our `numpy::array_view` wrappers instead, e.g.

https://github.com/matplotlib/matplotlib/blob/bc972942bd41a32c7cd693a3f29a29442d2d6e3f/src/_contour.cpp#L440

as it is simpler and deals with reference counting and raising exceptions for us.

Self-assigning.

### PR DESCRIPTION
**Pull request by QuLogic**
## PR Summary

Converting the Qhull wrapper to use `array_view` means converting it to C++, but also means doing some rework to avoid `goto` and use destructors for cleanup instead. This works better with any exception flow.

Fixes #19627 with #19918.

## PR Checklist

- [x] Has pytest style unit tests (and `pytest` passes).
- [x] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [n/a] New features are documented, with examples if plot related.
- [n/a] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [x] Conforms to Matplotlib style conventions (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).
- [n/a] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [n/a] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

### CODE REVIEW

File: src/qhull_wrap.cpp [hunk 1]
```diff
@@ -168,107 +193,71 @@ delaunay_impl(int npoints, const double* x, const double* y,
...
+    PyTuple_SET_ITEM(tuple, 1, neighbors.pyobj());
+    return tuple;
 }
 
-/* Process python arguments and call Delaunay implementation method. */
+/* Process Python arguments and call Delaunay implementation method. */
 static PyObject*
 delaunay(PyObject *self, PyObject *args)
 {
     PyObject* xarg;
```
Comment (ianthomas23) [inline src/qhull_wrap.cpp:255]: You could use the `array_view` converters to avoid having to have any `PyObject*` in this function.  Something like
https://github.com/QuLogic/matplotlib/blob/c62ca9a54d50b91ca971af955fe0f3760bd5deae/src/tri/_tri_wrapper.cpp#L33-L43

**Review by ianthomas23 — CHANGES_REQUESTED** [review]

**Comment by ianthomas23** [comment]
Sad to see the correction of one of my typos that has been here since 2013 :smiley:

File: src/qhull_wrap.cpp (hunk 1 above)
Comment (QuLogic) [reply src/qhull_wrap.cpp:255]: Right, I forgot to check if those existed.

**Review by ianthomas23 — APPROVED** [review]
