### PR TITLE
Switch PyArg_ParseTupleAndKeywords from "es" to "s".

### LINKED ISSUE #13865: Appveyor broken
Looks like https://github.com/matplotlib/matplotlib/pull/13836(?) broke Appveyor on 3.7 and should be reverted for now.

### PR DESCRIPTION
**Pull request by anntzer**
This avoids having to call PyMem_Free ourselves.

Note that all call sites either already use utf-8 (which "s" does), or
use ascii but then match the string against some ascii-only strings (or
glyph names), so the change is fine encoding-wise.

Perhaps this will fix #13865? (which fails with a MemoryError in get_sfnt_table)

edit: well no, this segfaults the doc build.
edit: duh, should be fixed now.

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by timhoffm** [comment]
The documentation of `es`  @says (https://docs.python.org/3/c-api/arg.html#strings-and-buffers):

> The caller is responsible for calling `PyMem_Free()` to free the allocated buffer after use.

How does this match with your statement

> This avoids having to call PyMem_Free ourselves.

**Comment by anntzer** [comment]
This PR switches from using "es" (which requires manual deallocation) to "s" (which doesn't).

**Comment by timhoffm** [comment]
Sorry, I was confused.

File: src/ft2font_wrapper.cpp [hunk 1]
```diff
@@ -1066,15 +1066,10 @@ static PyObject *PyFT2Font_get_name_index(PyFT2Font *self, PyObject *args, PyObj
 {
     char *glyphname;
```
Comment (QuLogic) [inline src/ft2font_wrapper.cpp]: No `const` here in this file?

Comment (anntzer) [reply src/ft2font_wrapper.cpp]: FT_Get_Name_Index takes a non-const char\* as argument (so we'd need a const_cast... not really worth it IMO? can add it if you prefer), even though it does not actually modify it.  See also thread starting at http://lists.nongnu.org/archive/html/freetype/2019-04/msg00004.html.
